name: validate_fasta_database
owner: caleb-easterly
description: runs Compomics database identification tool on any FASTA database. Separates well and poorly formatted entries in a FASTA database
homepage_url: http://www.github.com/caleb-easterly/FastaHeader
type: unrestricted
